import { ChangeEvent, useEffect, useMemo, useRef, useState } from 'react';
import { AnimatePresence, motion } from 'motion/react';
import { Copy, Download, ImagePlus, Link2, Mic, QrCode, Sparkles, Wand2, X } from 'lucide-react';
import { toPng } from 'html-to-image';
import QRCode from 'qrcode';
import { useLanguage } from '../context/LanguageContext';
import { createCardShareUrl } from '../lib/microSkillShare';

type CardData = {
  template?: 'tech-noir' | 'executive-minimal' | 'fashion-editorial';
  name: string | null;
  title: string | null;
  company: string | null;
  phone: string | null;
  email: string | null;
  social: string | null;
  insight: string;
  tagline?: string | null;
  motif?: string | null;
  typographyTone?: 'precision' | 'editorial' | 'monument';
  spacingDensity?: 'compact' | 'balanced' | 'airy';
  ornamentLevel?: 'subtle' | 'medium' | 'expressive';
  compositionType?: 'split' | 'stacked' | 'asymmetrical';
  confidence: number;
  themeMode: 'dark' | 'light';
  primaryColor: string;
  secondaryColor: string;
  layout: 'minimal' | 'bold' | 'tech';
  background: 'glassmorphism' | 'solid' | 'gradient';
};

const defaultPrompt = '我是 Kevin，全栈开发者，偏爱暗黑极客风，邮箱 kevin@mofang.ai，微信 kevinlab。';

const cardTemplates = [
  { id: 'tech-noir', label: 'Tech Noir' },
  { id: 'executive-minimal', label: 'Executive Minimal' },
  { id: 'fashion-editorial', label: 'Fashion Editorial' },
] as const;

type CardTemplateId = typeof cardTemplates[number]['id'];

const templateThemes = [
  { primary: '#22d3ee', secondary: '#a78bfa', layout: 'tech', background: 'gradient', mode: 'dark' },
  { primary: '#34d399', secondary: '#0f172a', layout: 'minimal', background: 'glassmorphism', mode: 'dark' },
  { primary: '#f59e0b', secondary: '#1f2937', layout: 'bold', background: 'solid', mode: 'dark' },
] as const;

async function readJsonResponse<T>(response: Response): Promise<T> {
  const text = await response.text();
  return JSON.parse(text) as T;
}

function downloadFile(filename: string, url: string) {
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  link.click();
}

function escapeXml(value: string) {
  return value
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&apos;');
}

function createCardSvg(card: CardData) {
  const name = escapeXml(card.name || 'Name Pending');
  const title = escapeXml(card.title || 'Role Pending');
  const company = escapeXml(card.company || card.tagline || 'MOFANG AI generated identity');
  const email = escapeXml(card.email || 'email@placeholder.ai');
  const meta = escapeXml(card.phone || card.social || 'WeChat / Phone pending');
  const insight = escapeXml(card.insight || 'Generated by MOFANG AI');
  const tagline = escapeXml(card.tagline || card.motif || 'Adaptive identity system');
  const template = card.template || 'tech-noir';

  if (template === 'executive-minimal') {
    return `
<svg xmlns="http://www.w3.org/2000/svg" width="1200" height="720" viewBox="0 0 1200 720">
  <defs>
    <linearGradient id="line" x1="0%" y1="0%" x2="100%" y2="0%">
      <stop offset="0%" stop-color="${card.primaryColor}"/>
      <stop offset="100%" stop-color="${card.secondaryColor}"/>
    </linearGradient>
  </defs>
  <rect width="1200" height="720" rx="48" fill="#0a0b10"/>
  <rect x="40" y="40" width="1120" height="640" rx="38" fill="#101117" stroke="rgba(255,255,255,0.10)"/>
  <rect x="86" y="92" width="1028" height="2" fill="url(#line)"/>
  <text x="86" y="150" fill="#8b97a8" font-family="Inter, Arial, sans-serif" font-size="18" letter-spacing="6">EXECUTIVE MINIMAL</text>
  <text x="86" y="270" fill="#ffffff" font-family="Inter, Arial, sans-serif" font-size="96" font-weight="700">${name}</text>
  <text x="86" y="324" fill="#d4d4d8" font-family="Inter, Arial, sans-serif" font-size="32">${title}</text>
  <text x="86" y="362" fill="#8b97a8" font-family="Inter, Arial, sans-serif" font-size="24">${company}</text>
  <text x="86" y="442" fill="${card.primaryColor}" font-family="Inter, Arial, sans-serif" font-size="24">${tagline}</text>
  <rect x="86" y="500" width="474" height="118" rx="26" fill="rgba(255,255,255,0.025)" stroke="rgba(255,255,255,0.09)"/>
  <rect x="588" y="500" width="526" height="118" rx="26" fill="rgba(255,255,255,0.025)" stroke="rgba(255,255,255,0.09)"/>
  <text x="118" y="546" fill="#7a8493" font-family="Inter, Arial, sans-serif" font-size="16" letter-spacing="4">CONTACT</text>
  <text x="118" y="585" fill="#ffffff" font-family="Inter, Arial, sans-serif" font-size="26">${email}</text>
  <text x="118" y="620" fill="#a1a1aa" font-family="Inter, Arial, sans-serif" font-size="21">${meta}</text>
  <text x="620" y="546" fill="#7a8493" font-family="Inter, Arial, sans-serif" font-size="16" letter-spacing="4">DESIGN NOTE</text>
  <text x="620" y="585" fill="#ffffff" font-family="Inter, Arial, sans-serif" font-size="24">${insight}</text>
</svg>`.trim();
  }

  if (template === 'fashion-editorial') {
    return `
<svg xmlns="http://www.w3.org/2000/svg" width="1200" height="720" viewBox="0 0 1200 720">
  <defs>
    <linearGradient id="wash" x1="0%" y1="0%" x2="100%" y2="100%">
      <stop offset="0%" stop-color="${card.primaryColor}" stop-opacity="0.24"/>
      <stop offset="100%" stop-color="${card.secondaryColor}" stop-opacity="0.18"/>
    </linearGradient>
  </defs>
  <rect width="1200" height="720" rx="48" fill="#09090b"/>
  <rect x="34" y="34" width="1132" height="652" rx="40" fill="url(#wash)"/>
  <rect x="56" y="56" width="1088" height="608" rx="34" fill="#0b0b10" stroke="rgba(255,255,255,0.10)"/>
  <text x="86" y="126" fill="#8f8fa0" font-family="Inter, Arial, sans-serif" font-size="18" letter-spacing="7">FASHION EDITORIAL</text>
  <text x="86" y="242" fill="#ffffff" font-family="Inter, Arial, sans-serif" font-size="40">${tagline}</text>
  <text x="82" y="392" fill="#ffffff" font-family="Inter, Arial, sans-serif" font-size="118" font-weight="700">${name}</text>
  <text x="86" y="448" fill="#d4d4d8" font-family="Inter, Arial, sans-serif" font-size="34">${title}</text>
  <text x="86" y="488" fill="#8f8fa0" font-family="Inter, Arial, sans-serif" font-size="24">${company}</text>
  <rect x="784" y="108" width="286" height="418" rx="28" fill="rgba(255,255,255,0.03)" stroke="rgba(255,255,255,0.10)"/>
  <circle cx="927" cy="217" r="74" fill="${card.primaryColor}" fill-opacity="0.16"/>
  <circle cx="927" cy="217" r="30" fill="${card.secondaryColor}" fill-opacity="0.18"/>
  <text x="820" y="344" fill="#7a8493" font-family="Inter, Arial, sans-serif" font-size="15" letter-spacing="4">DESIGN LOGIC</text>
  <text x="820" y="388" fill="#ffffff" font-family="Inter, Arial, sans-serif" font-size="23">${insight}</text>
  <rect x="86" y="552" width="984" height="80" rx="26" fill="rgba(255,255,255,0.03)" stroke="rgba(255,255,255,0.10)"/>
  <text x="118" y="602" fill="#ffffff" font-family="Inter, Arial, sans-serif" font-size="26">${email}</text>
  <text x="720" y="602" fill="#a1a1aa" font-family="Inter, Arial, sans-serif" font-size="23">${meta}</text>
</svg>`.trim();
  }

  return `
<svg xmlns="http://www.w3.org/2000/svg" width="1200" height="720" viewBox="0 0 1200 720">
  <defs>
    <linearGradient id="bg" x1="0%" y1="0%" x2="100%" y2="100%">
      <stop offset="0%" stop-color="${card.primaryColor}" stop-opacity="0.28"/>
      <stop offset="100%" stop-color="${card.secondaryColor}" stop-opacity="0.18"/>
    </linearGradient>
    <linearGradient id="edge" x1="0%" y1="0%" x2="100%" y2="0%">
      <stop offset="0%" stop-color="${card.primaryColor}"/>
      <stop offset="100%" stop-color="${card.secondaryColor}"/>
    </linearGradient>
  </defs>
  <rect width="1200" height="720" rx="48" fill="#09090b"/>
  <rect x="24" y="24" width="1152" height="672" rx="40" fill="url(#bg)" />
  <rect x="56" y="56" width="1088" height="608" rx="36" fill="#0a0b10" stroke="rgba(255,255,255,0.12)"/>
  <rect x="88" y="88" width="10" height="544" rx="5" fill="url(#edge)"/>
  <rect x="104" y="96" width="250" height="56" rx="28" fill="rgba(255,255,255,0.04)" stroke="rgba(255,255,255,0.10)"/>
  <text x="136" y="132" fill="#d4d4d8" font-family="Inter, Arial, sans-serif" font-size="18" letter-spacing="5">ONE-PROMPT CARD</text>
  <text x="104" y="238" fill="#ffffff" font-family="Inter, Arial, sans-serif" font-weight="700" font-size="88">${name}</text>
  <text x="104" y="294" fill="#d4d4d8" font-family="Inter, Arial, sans-serif" font-size="34">${title}</text>
  <text x="104" y="334" fill="#a1a1aa" font-family="Inter, Arial, sans-serif" font-size="24">${company}</text>
  <text x="104" y="388" fill="#8be8ff" font-family="Inter, Arial, sans-serif" font-size="22">${tagline}</text>
  <rect x="104" y="446" width="420" height="136" rx="30" fill="rgba(255,255,255,0.03)" stroke="rgba(255,255,255,0.10)"/>
  <rect x="548" y="446" width="510" height="136" rx="30" fill="rgba(255,255,255,0.03)" stroke="rgba(255,255,255,0.10)"/>
  <text x="140" y="494" fill="#71717a" font-family="Inter, Arial, sans-serif" font-size="18" letter-spacing="4">CONTACT</text>
  <text x="140" y="536" fill="#ffffff" font-family="Inter, Arial, sans-serif" font-size="28">${email}</text>
  <text x="140" y="574" fill="#a1a1aa" font-family="Inter, Arial, sans-serif" font-size="22">${meta}</text>
  <text x="584" y="494" fill="#71717a" font-family="Inter, Arial, sans-serif" font-size="18" letter-spacing="4">DESIGN LOGIC</text>
  <text x="584" y="536" fill="#ffffff" font-family="Inter, Arial, sans-serif" font-size="26">${insight}</text>
  <text x="584" y="574" fill="#a1a1aa" font-family="Inter, Arial, sans-serif" font-size="22">${escapeXml(card.layout)} / ${escapeXml(card.background)}</text>
  <circle cx="984" cy="176" r="94" fill="rgba(255,255,255,0.04)" stroke="rgba(255,255,255,0.10)"/>
  <circle cx="984" cy="176" r="60" fill="${card.primaryColor}" fill-opacity="0.14"/>
  <circle cx="984" cy="176" r="26" fill="${card.secondaryColor}" fill-opacity="0.22"/>
</svg>`.trim();
}

function inferName(prompt: string) {
  const patterns = [
    /我叫([A-Za-z\u4e00-\u9fa5·]+)/,
    /我是([A-Za-z\u4e00-\u9fa5·]+)/,
    /叫我([A-Za-z\u4e00-\u9fa5·]+)/,
    /name[:：]?\s*([A-Za-z\u4e00-\u9fa5·]+)/i,
  ];

  for (const pattern of patterns) {
    const match = prompt.match(pattern);
    if (match?.[1]) {
      return match[1].replace(/老师|总|哥|姐|就行|哈|呀/g, '');
    }
  }

  return null;
}

function inferField(prompt: string, patterns: RegExp[]) {
  for (const pattern of patterns) {
    const match = prompt.match(pattern);
    if (match?.[1]) return match[1];
  }
  return null;
}

function createCard(prompt: string, imageColor?: string | null): CardData {
  const name = inferName(prompt);
  const email = inferField(prompt, [/([A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,})/i]);
  const phone = inferField(prompt, [/(1[3-9]\d{9})/, /(\+?\d[\d\s-]{7,}\d)/]);
  const social = inferField(prompt, [/微信[是:： ]?([A-Za-z0-9_-]+)/, /twitter[是:： ]?([A-Za-z0-9_]+)/i]);
  const company = inferField(prompt, [/在(.+?)工作/, /来自(.+?)(?:，|。|,)/, /(.+?)的(设计师|开发者|创始人|产品经理|顾问)/]);
  const title = inferField(prompt, [/(全栈开发者|设计师|独立游戏开发者|产品经理|创始人|顾问|程序员|运营负责人|导演|摄影师)/]);
  const confidence = name ? 0.92 : 0.48;
  const theme =
    prompt.includes('极简') ? templateThemes[1] :
    prompt.includes('金融') ? templateThemes[2] :
    templateThemes[0];

  return {
    template: theme.layout === 'minimal' ? 'executive-minimal' : theme.layout === 'bold' ? 'fashion-editorial' : 'tech-noir',
    name,
    title,
    company,
    phone,
    email,
    social,
    insight: confidence > 0.8 ? '已匹配高科技深色主题' : '检测到称呼可能有歧义，请点按名片修正',
    tagline: prompt.includes('极简') ? 'Structured clarity' : 'Signal-ready identity',
    motif: prompt.includes('极简') ? 'soft border' : 'neon grid',
    typographyTone: theme.layout === 'minimal' ? 'precision' : theme.layout === 'bold' ? 'editorial' : 'monument',
    spacingDensity: theme.layout === 'minimal' ? 'airy' : 'balanced',
    ornamentLevel: theme.layout === 'bold' ? 'expressive' : theme.layout === 'minimal' ? 'subtle' : 'medium',
    compositionType: theme.layout === 'minimal' ? 'stacked' : theme.layout === 'bold' ? 'asymmetrical' : 'split',
    confidence,
    themeMode: theme.mode,
    primaryColor: imageColor || theme.primary,
    secondaryColor: theme.secondary,
    layout: theme.layout,
    background: theme.background,
  };
}

function getTemplateLabel(template?: CardTemplateId | null) {
  return cardTemplates.find((item) => item.id === template)?.label || 'Tech Noir';
}

function getCardShellBackground(card: CardData | null) {
  if (!card) return 'linear-gradient(135deg, #111114 0%, #050505 100%)';
  if (card.template === 'executive-minimal') {
    return `linear-gradient(180deg, #12141b 0%, #0a0c11 100%)`;
  }
  if (card.template === 'fashion-editorial') {
    return `radial-gradient(circle at 18% 18%, ${card.primaryColor}22, transparent 28%), radial-gradient(circle at 82% 16%, ${card.secondaryColor}18, transparent 22%), linear-gradient(145deg, #140f13 0%, #08080b 100%)`;
  }
  return `radial-gradient(circle at top left, ${card.primaryColor}26, transparent 34%), radial-gradient(circle at 85% 12%, ${card.secondaryColor}16, transparent 22%), linear-gradient(145deg, #121218 0%, #06070b 100%)`;
}

function getSpacingClasses(card: CardData | null) {
  if (!card || card.spacingDensity === 'balanced') {
    return {
      section: 'mb-8',
      stack: 'gap-4',
      title: 'mt-3',
    };
  }

  if (card.spacingDensity === 'airy') {
    return {
      section: 'mb-10',
      stack: 'gap-5',
      title: 'mt-4',
    };
  }

  return {
    section: 'mb-6',
    stack: 'gap-3',
    title: 'mt-2',
  };
}

function getCompositionGrid(card: CardData | null) {
  if (!card || card.compositionType === 'split') {
    return 'md:grid-cols-2';
  }
  if (card.compositionType === 'stacked') {
    return 'md:grid-cols-1';
  }
  return 'md:grid-cols-[1.2fr_0.8fr]';
}

async function extractAverageColor(file: File) {
  const dataUrl = await new Promise<string>((resolve, reject) => {
    const reader = new FileReader();
    reader.onload = () => resolve(String(reader.result));
    reader.onerror = () => reject(new Error('Image read failed.'));
    reader.readAsDataURL(file);
  });

  const img = await new Promise<HTMLImageElement>((resolve, reject) => {
    const image = new Image();
    image.onload = () => resolve(image);
    image.onerror = () => reject(new Error('Image load failed.'));
    image.src = dataUrl;
  });

  const canvas = document.createElement('canvas');
  canvas.width = 32;
  canvas.height = 32;
  const context = canvas.getContext('2d');
  if (!context) return '#22d3ee';
  context.drawImage(img, 0, 0, 32, 32);
  const { data } = context.getImageData(0, 0, 32, 32);

  let r = 0;
  let g = 0;
  let b = 0;
  const count = data.length / 4;
  for (let index = 0; index < data.length; index += 4) {
    r += data[index];
    g += data[index + 1];
    b += data[index + 2];
  }

  return `#${[r, g, b].map((value) => Math.round(value / count).toString(16).padStart(2, '0')).join('')}`;
}

async function compressImage(file: File) {
  const rawDataUrl = await new Promise<string>((resolve, reject) => {
    const reader = new FileReader();
    reader.onload = () => resolve(String(reader.result));
    reader.onerror = () => reject(new Error('Image read failed.'));
    reader.readAsDataURL(file);
  });

  const img = await new Promise<HTMLImageElement>((resolve, reject) => {
    const image = new Image();
    image.onload = () => resolve(image);
    image.onerror = () => reject(new Error('Image load failed.'));
    image.src = rawDataUrl;
  });

  const canvas = document.createElement('canvas');
  const maxWidth = 768;
  const scale = Math.min(1, maxWidth / img.width);
  canvas.width = Math.max(1, Math.round(img.width * scale));
  canvas.height = Math.max(1, Math.round(img.height * scale));
  const context = canvas.getContext('2d');
  if (!context) return rawDataUrl;
  context.drawImage(img, 0, 0, canvas.width, canvas.height);
  return canvas.toDataURL('image/jpeg', 0.82);
}

export default function MicroSkillSandbox({ open, onClose }: { open: boolean; onClose: () => void }) {
  const { t } = useLanguage();
  const [prompt, setPrompt] = useState(defaultPrompt);
  const [logs, setLogs] = useState<string[]>([]);
  const [card, setCard] = useState<CardData | null>(null);
  const [isGenerating, setIsGenerating] = useState(false);
  const [imageColor, setImageColor] = useState<string | null>(null);
  const [imageDataUrl, setImageDataUrl] = useState<string | null>(null);
  const [nameOverride, setNameOverride] = useState('');
  const [editingName, setEditingName] = useState(false);
  const [shareUrl, setShareUrl] = useState('');
  const [qrDataUrl, setQrDataUrl] = useState('');
  const [templateOverride, setTemplateOverride] = useState<CardTemplateId | null>(null);
  const timerRef = useRef<number[]>([]);
  const cardRef = useRef<HTMLDivElement | null>(null);

  useEffect(() => {
    return () => {
      timerRef.current.forEach((timer) => window.clearTimeout(timer));
    };
  }, []);

  const effectiveCard = useMemo(() => {
    if (!card) return null;
    return {
      ...card,
      template: templateOverride || card.template || 'tech-noir',
      name: editingName ? nameOverride : (nameOverride || card.name),
    };
  }, [card, editingName, nameOverride, templateOverride]);

  useEffect(() => {
    if (!effectiveCard) {
      setShareUrl('');
      setQrDataUrl('');
      return;
    }

    const nextUrl = createCardShareUrl(effectiveCard);
    setShareUrl(nextUrl);
    void QRCode.toDataURL(nextUrl, {
      margin: 1,
      width: 180,
      color: {
        dark: '#ffffff',
        light: '#00000000',
      },
    }).then(setQrDataUrl);
  }, [effectiveCard]);

  const spacing = useMemo(() => getSpacingClasses(effectiveCard), [effectiveCard]);
  const compositionGrid = useMemo(() => getCompositionGrid(effectiveCard), [effectiveCard]);

  const runGenerate = async () => {
    setIsGenerating(true);
    setLogs([]);
    setCard(null);

    const stagedLogs = [
      t('micro.log1'),
      t('micro.log2'),
      t('micro.log3'),
      t('micro.log4'),
    ];

    stagedLogs.forEach((line, index) => {
      const timer = window.setTimeout(() => {
        setLogs((prev) => [...prev, line]);
      }, index * 550);
      timerRef.current.push(timer);
    });

    const timer = window.setTimeout(async () => {
      try {
        const response = await fetch('/api/micro-skill', {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
          },
          body: JSON.stringify({
            prompt,
            imageColor,
            imageDataUrl,
          }),
        });

        const result = await readJsonResponse<{ ok: boolean; card?: CardData; message?: string }>(response);
        if (!response.ok || !result.ok || !result.card) {
          throw new Error(result.message || 'Micro-skill generation failed.');
        }

        setCard(result.card);
        setNameOverride(result.card.name || '');
        setTemplateOverride(result.card.template || null);
      } catch {
        const fallbackCard = createCard(prompt, imageColor);
        setCard(fallbackCard);
        setNameOverride(fallbackCard.name || '');
        setTemplateOverride(fallbackCard.template || null);
        setLogs((prev) => [...prev, t('micro.fallback')]);
      } finally {
        setEditingName(false);
        setIsGenerating(false);
      }
    }, stagedLogs.length * 550 + 350);

    timerRef.current.push(timer);
  };

  const onImageChange = async (event: ChangeEvent<HTMLInputElement>) => {
    const file = event.target.files?.[0];
    if (!file) return;
    const [color, compressed] = await Promise.all([extractAverageColor(file), compressImage(file)]);
    setImageColor(color);
    setImageDataUrl(compressed);
  };

  const handleDownloadPng = async () => {
    if (!cardRef.current || !effectiveCard) return;
    const dataUrl = await toPng(cardRef.current, {
      cacheBust: true,
      pixelRatio: 2,
      backgroundColor: '#09090b',
    });
    downloadFile(`${(effectiveCard.name || 'one-prompt-card').replace(/\s+/g, '-').toLowerCase()}.png`, dataUrl);
  };

  const handleDownloadSvg = () => {
    if (!effectiveCard) return;
    const svg = createCardSvg(effectiveCard);
    const blob = new Blob([svg], { type: 'image/svg+xml;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    downloadFile(`${(effectiveCard.name || 'one-prompt-card').replace(/\s+/g, '-').toLowerCase()}.svg`, url);
    window.setTimeout(() => URL.revokeObjectURL(url), 1000);
  };

  const handleCopyShareUrl = async () => {
    if (!shareUrl) return;
    await navigator.clipboard.writeText(shareUrl);
    setLogs((prev) => [...prev, t('micro.linkCopied')]);
  };

  return (
    <AnimatePresence>
      {open ? (
        <motion.div
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          exit={{ opacity: 0 }}
          className="fixed inset-0 z-[80] bg-black/70 backdrop-blur-md px-4 py-6 overflow-auto"
        >
          <div className="mx-auto max-w-6xl min-h-full flex items-center">
            <motion.div
              initial={{ opacity: 0, y: 30, scale: 0.98 }}
              animate={{ opacity: 1, y: 0, scale: 1 }}
              exit={{ opacity: 0, y: 20, scale: 0.98 }}
              className="w-full glass-panel rounded-[2.5rem] border border-white/10 p-6 md:p-10 relative"
            >
              <button onClick={onClose} className="absolute top-5 right-5 rounded-full border border-white/10 bg-white/5 p-3 text-zinc-400 hover:text-white transition-colors">
                <X className="w-4 h-4" />
              </button>

              <div className="max-w-2xl">
                <p className="text-cyan-300 uppercase tracking-[0.35em] text-xs">{t('micro.eyebrow')}</p>
                <h2 className="mt-4 text-4xl md:text-6xl font-semibold tracking-tight">{t('micro.title')}</h2>
                <p className="mt-4 text-zinc-400 text-lg leading-8">{t('micro.desc')}</p>
              </div>

              <div className="mt-10 grid gap-6 xl:grid-cols-[0.92fr_1.08fr] items-start">
                <div className="rounded-[2rem] border border-white/10 bg-black/35 p-5 md:p-6">
                  <div className="flex gap-3 mb-4">
                    <button type="button" className="rounded-2xl border border-white/10 bg-white/5 p-3 text-zinc-400">
                      <Mic className="w-4 h-4" />
                    </button>
                    <label className="rounded-2xl border border-white/10 bg-white/5 p-3 text-zinc-400 cursor-pointer">
                      <ImagePlus className="w-4 h-4" />
                      <input type="file" accept="image/*" className="hidden" onChange={onImageChange} />
                    </label>
                    <button onClick={runGenerate} disabled={isGenerating} className="ml-auto inline-flex items-center gap-2 rounded-2xl bg-white text-black px-5 py-3 font-medium disabled:opacity-60">
                      <Wand2 className="w-4 h-4" />
                      {t('micro.generate')}
                    </button>
                  </div>

                  <textarea
                    value={prompt}
                    onChange={(event) => setPrompt(event.target.value)}
                    placeholder={t('micro.placeholder')}
                    rows={7}
                    className="w-full rounded-[1.5rem] border border-white/10 bg-black/60 px-5 py-4 text-white placeholder:text-zinc-600 resize-none focus:outline-none focus:border-cyan-500/50"
                  />

                  <div className="mt-5 rounded-[1.5rem] border border-white/10 bg-[#09090b] p-4 min-h-[190px] font-mono text-sm text-zinc-400">
                    {logs.length ? logs.map((line, index) => (
                      <div key={`${line}-${index}`} className="mb-2 last:mb-0">{line}</div>
                    )) : <div className="text-zinc-600">{t('micro.consoleIdle')}</div>}
                  </div>
                </div>

                <div className="rounded-[2rem] border border-white/10 bg-black/35 p-5 md:p-6">
                  <div className="mb-5 flex flex-wrap gap-2">
                    {cardTemplates.map((item) => {
                      const active = (effectiveCard?.template || 'tech-noir') === item.id;
                      return (
                        <button
                          key={item.id}
                          type="button"
                          onClick={() => setTemplateOverride(item.id)}
                          className={`rounded-full border px-3 py-1.5 text-xs tracking-[0.24em] uppercase transition-colors ${active ? 'border-cyan-400/50 bg-cyan-400/12 text-cyan-100' : 'border-white/10 bg-white/5 text-zinc-400 hover:text-white'}`}
                        >
                          {item.label}
                        </button>
                      );
                    })}
                  </div>
                  <div
                    ref={cardRef}
                    className="rounded-[2rem] border border-white/10 p-8 md:p-10 min-h-[540px] relative overflow-hidden"
                    style={{ background: getCardShellBackground(effectiveCard) }}
                  >
                    <div className="absolute inset-0 bg-[radial-gradient(circle_at_top_right,rgba(255,255,255,0.08),transparent_30%)]" />
                    {effectiveCard?.template !== 'fashion-editorial' ? (
                      <div className="absolute left-6 top-8 bottom-8 w-[6px] rounded-full" style={{ background: effectiveCard ? `linear-gradient(180deg, ${effectiveCard.primaryColor}, ${effectiveCard.secondaryColor})` : 'linear-gradient(180deg, #22d3ee, #a78bfa)' }} />
                    ) : null}
                    {effectiveCard?.template === 'fashion-editorial' ? (
                      <div className={`absolute right-8 top-8 ${effectiveCard.ornamentLevel === 'expressive' ? 'h-[20rem] w-[20rem] opacity-40' : 'h-[16rem] w-[16rem] opacity-25'} rounded-full blur-3xl`} style={{ background: `radial-gradient(circle, ${effectiveCard.primaryColor}, transparent 68%)` }} />
                    ) : null}
                    {effectiveCard?.template === 'executive-minimal' ? (
                      <div className="absolute left-10 right-10 top-14 h-px" style={{ background: `linear-gradient(90deg, transparent, ${effectiveCard.primaryColor}, ${effectiveCard.secondaryColor}, transparent)` }} />
                    ) : null}
                    <div className="relative z-10">
                      <div className={`flex items-center gap-3 mb-8 ${effectiveCard?.template === 'fashion-editorial' ? '' : 'pl-5'}`}>
                        <div className="w-12 h-12 rounded-2xl border border-white/10 bg-white/5 flex items-center justify-center shadow-[0_0_40px_rgba(34,211,238,0.12)]">
                          <Sparkles className="w-5 h-5" style={{ color: effectiveCard?.primaryColor || '#22d3ee' }} />
                        </div>
                        <div>
                          <p className="text-xs uppercase tracking-[0.3em] text-zinc-500">{t('micro.cardLabel')}</p>
                          <p className="text-sm text-zinc-400">{effectiveCard?.insight || t('micro.cardHint')}</p>
                        </div>
                      </div>

                      {effectiveCard ? (
                        <>
                          <div className={`${spacing.section} ${effectiveCard.template === 'fashion-editorial' ? '' : 'pl-5'}`}>
                            <div className={`mb-5 inline-flex items-center gap-2 rounded-full border border-white/10 bg-white/5 px-4 py-2 text-[11px] uppercase tracking-[0.35em] text-zinc-400 ${effectiveCard.template === 'executive-minimal' ? 'bg-transparent' : ''}`}>
                              <span className="inline-block h-2 w-2 rounded-full" style={{ backgroundColor: effectiveCard.primaryColor }} />
                              {getTemplateLabel(effectiveCard.template)}
                            </div>
                            {editingName ? (
                              <input
                                value={nameOverride}
                                onChange={(event) => setNameOverride(event.target.value)}
                                onBlur={() => setEditingName(false)}
                                autoFocus
                                className="bg-transparent text-4xl md:text-5xl font-semibold tracking-tight text-white border-b border-cyan-400/40 focus:outline-none"
                              />
                            ) : (
                              <button onClick={() => setEditingName(true)} className="text-left">
                                <div className={`${effectiveCard.template === 'fashion-editorial' ? 'text-5xl md:text-7xl' : effectiveCard.template === 'executive-minimal' ? 'text-4xl md:text-6xl' : 'text-4xl md:text-5xl'} ${effectiveCard.typographyTone === 'precision' ? 'tracking-[0.02em]' : effectiveCard.typographyTone === 'editorial' ? 'tracking-[-0.04em]' : 'tracking-tight'} font-semibold text-white`}>
                                  {effectiveCard.name || t('micro.nameFallback')}
                                </div>
                              </button>
                            )}
                            <p className={`${effectiveCard.template === 'fashion-editorial' ? 'text-2xl md:text-3xl' : effectiveCard.template === 'executive-minimal' ? 'text-xl uppercase tracking-[0.25em]' : 'text-lg'} ${spacing.title} text-zinc-300`}>{effectiveCard.title || t('micro.roleFallback')}</p>
                            <p className={`mt-2 ${effectiveCard.template === 'fashion-editorial' ? 'text-base md:text-lg' : ''} text-zinc-500`}>{effectiveCard.company || t('micro.companyFallback')}</p>
                            {effectiveCard.tagline ? (
                              <p className={`${effectiveCard.template === 'fashion-editorial' ? 'mt-6 text-3xl md:text-4xl max-w-lg leading-tight' : 'mt-5 text-sm uppercase tracking-[0.35em]'} text-zinc-300`}>
                                {effectiveCard.tagline}
                              </p>
                            ) : null}
                          </div>

                          <div className={`grid ${spacing.stack} ${effectiveCard.template === 'fashion-editorial' ? 'md:grid-cols-[1.15fr_0.85fr]' : effectiveCard.template === 'executive-minimal' ? (effectiveCard.compositionType === 'stacked' ? 'md:grid-cols-1' : 'md:grid-cols-[0.9fr_1.1fr]') : compositionGrid}`}>
                            <div className="rounded-[1.5rem] border border-white/10 bg-black/40 p-5 backdrop-blur-xl">
                              <p className="text-xs uppercase tracking-[0.3em] text-zinc-500 mb-3">{effectiveCard.template === 'fashion-editorial' ? 'DIRECT CHANNEL' : 'Contact'}</p>
                              <p className="text-zinc-200">{effectiveCard.email || 'email@placeholder.ai'}</p>
                              <p className="text-zinc-400 mt-2">{effectiveCard.phone || effectiveCard.social || 'WeChat / Phone pending'}</p>
                            </div>
                            <div className="rounded-[1.5rem] border border-white/10 bg-black/40 p-5 backdrop-blur-xl">
                              <p className="text-xs uppercase tracking-[0.3em] text-zinc-500 mb-3">{effectiveCard.template === 'executive-minimal' ? 'BRAND RATIONALE' : 'Design Logic'}</p>
                              <p className="text-zinc-200 leading-7">{effectiveCard.insight}</p>
                              <p className="mt-2 text-zinc-400">{effectiveCard.layout} / {effectiveCard.background} / {effectiveCard.typographyTone} / {effectiveCard.compositionType} / {Math.round(effectiveCard.confidence * 100)}% name confidence</p>
                            </div>
                          </div>

                          {effectiveCard.template === 'fashion-editorial' ? (
                            <div className={`mt-4 grid gap-4 ${effectiveCard.compositionType === 'stacked' ? 'md:grid-cols-1' : 'md:grid-cols-[1fr_10rem]'}`}>
                              <div className="rounded-[1.5rem] border border-white/10 bg-white/[0.03] px-5 py-4 text-sm text-zinc-400">
                                {effectiveCard.motif ? `Visual motif: ${effectiveCard.motif}` : 'Visual motif: premium editorial composition'}
                              </div>
                              <div className="rounded-[1.5rem] border border-white/10 bg-white/[0.03] px-5 py-4 text-right">
                                <p className="text-xs uppercase tracking-[0.3em] text-zinc-500">Edition</p>
                                <p className="mt-2 text-2xl font-semibold text-white">03</p>
                              </div>
                            </div>
                          ) : (
                            <div className="mt-4 rounded-[1.5rem] border border-white/10 bg-white/[0.03] px-5 py-4 text-sm text-zinc-400">
                              {effectiveCard.motif ? `Visual motif: ${effectiveCard.motif}` : 'Visual motif: premium tech composition'}
                            </div>
                          )}
                        </>
                      ) : (
                        <div className="min-h-[360px] flex items-center justify-center text-center text-zinc-600">
                          {t('micro.previewEmpty')}
                        </div>
                      )}
                    </div>
                  </div>

                  <div className="mt-5 flex flex-col sm:flex-row gap-3">
                    <button onClick={handleDownloadPng} disabled={!effectiveCard} className="rounded-2xl border border-white/10 bg-white/5 px-5 py-3 text-zinc-300 inline-flex items-center justify-center gap-2 disabled:opacity-50">
                      <Download className="w-4 h-4" />
                      {t('micro.downloadPng')}
                    </button>
                    <button onClick={handleDownloadSvg} disabled={!effectiveCard} className="rounded-2xl border border-white/10 bg-white/5 px-5 py-3 text-zinc-300 inline-flex items-center justify-center gap-2 disabled:opacity-50">
                      <Download className="w-4 h-4" />
                      {t('micro.downloadSvg')}
                    </button>
                    <button onClick={handleCopyShareUrl} disabled={!shareUrl} className="rounded-2xl border border-white/10 bg-white/5 px-5 py-3 text-zinc-300 inline-flex items-center justify-center gap-2 disabled:opacity-50">
                      <Copy className="w-4 h-4" />
                      {t('micro.copyLink')}
                    </button>
                    <a href="#contact" onClick={onClose} className="rounded-2xl bg-white text-black px-5 py-3 font-medium text-center">
                      {t('micro.cta')}
                    </a>
                    <button onClick={() => setPrompt(defaultPrompt)} className="rounded-2xl border border-white/10 bg-white/5 px-5 py-3 text-zinc-300">
                      {t('micro.reset')}
                    </button>
                  </div>

                  {shareUrl ? (
                    <div className="mt-5 rounded-[1.5rem] border border-white/10 bg-black/40 p-4 md:p-5 flex flex-col md:flex-row gap-4 md:items-center">
                      <div className="w-[120px] h-[120px] rounded-2xl border border-white/10 bg-black/50 flex items-center justify-center shrink-0">
                        {qrDataUrl ? <img src={qrDataUrl} alt="Card QR code" className="w-[96px] h-[96px]" /> : <QrCode className="w-8 h-8 text-zinc-600" />}
                      </div>
                      <div className="min-w-0">
                        <p className="text-sm uppercase tracking-[0.3em] text-zinc-500 mb-2">{t('micro.qrTitle')}</p>
                        <div className="rounded-2xl border border-white/10 bg-white/5 px-4 py-3 text-sm text-zinc-300 break-all">
                          {shareUrl}
                        </div>
                        <p className="mt-3 text-sm text-zinc-500">{t('micro.qrDesc')}</p>
                      </div>
                    </div>
                  ) : null}
                </div>
              </div>
            </motion.div>
          </div>
        </motion.div>
      ) : null}
    </AnimatePresence>
  );
}
